### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by KavinduZoysa** [KavinduZoysa/test-GCs#2]
These are the list og JBUGs we need to update. 

- [ ] compiler/tests/testBalt.bal: `JBUG: #32575`
- [x] compiler/tests/testBalt.bal: `JBUG #32440 can't use assertNotEqual`
- [x] compiler/tests/testBalt.bal: `JBUG #31334 cast`
- [x] compiler/tests/testSuite.bal: `JBUG #31334 cast`
- [x] compiler/tests/testSuite.bal: `JBUG #31334 cast needed`
- [x] compiler/tests/testSuite.bal: `JBUG #32615 can't use from-in-from query syntax`
- [ ] compiler/tests/baltest.bal: `JBUG #31679 should use do`
- [ ] compiler/tests/data/float-singleton2.bal: `JBUG #28334 this is highlighted as an error`
- [ ] compiler/compile.bal: `JBUG gets a bad, sad when done with a query expression`
- [ ] compiler/balt.bal: `JBUG: can't use Char gives "'string' value 'x' cannot be converted to 'lang.string:Char'`
- [ ] compiler/modules/nback/typeTest.bal: `JBUG crash if 16 is 0xF`
- [ ] compiler/modules/nback/build.bal: `JBUG #31394 would be better to use shifts for these`
- [ ] compiler/modules/nback/build.bal: `JBUG #31753 cast`
- [ ] compiler/modules/nback/build.bal: `JBUG <int> cast needed (otherwise result is or'd with 0xFF)`
- [ ] compiler/modules/nback/scaffold.bal: `JBUG cast needed #31867`
- [ ] compiler/modules/nback/scaffold.bal: `JBUG this goes wrong when you use REPR_VOID as a type as in buildRet`
- [ ] compiler/modules/nback/equal.bal: `JBUG cast`
- [ ] compiler/modules/nback/structure.bal: `JBUG if I combine these statements into a single from/do, then it gives an assignment required error`
- [ ] compiler/modules/nback/structure.bal: `JBUG This doesn't work with array:sort (complains about unordered type)`
- [ ] compiler/modules/types/float.bal: `JBUG indexOf does not work with -0 because of #32245`
- [ ] compiler/modules/types/enumerable.bal: `JBUG: #17977`
- [ ] compiler/modules/types/core.bal: `JBUG #31751 bad, sad if UT_OBJECT_RW + 1`
- [ ] compiler/modules/front/const.bal: `JBUG toString should not be required`
- [ ] compiler/modules/front/symbols.bal: `JBUG Bad, sad without `names` variable`
- [ ] compiler/modules/front/codeGen.bal: `JBUG #31311 does not allow `outer` here`
- [ ] compiler/modules/front/codeGen.bal: `JBUG #31327 cast`
- [ ] compiler/modules/front/codeGen.bal: `JBUG #31327 cast`
- [ ] compiler/modules/front/codeGen.bal: `JBUG need parentheses`
- [ ] compiler/modules/front/codeGen.bal: `JBUG following line results in bad code`
- [ ] compiler/modules/front/codeGen.bal: ``JBUG changing `returns` to `return` makes the parse get a NPE during error recovery``
- [ ] compiler/modules/front/codeGen.bal: `JBUG without parentheses this gets a parse error`
- [ ] compiler/modules/front/codeGen.bal: `JBUG #31782 cast needed`
- [ ] compiler/modules/front/codeGen.bal: `JBUG does not work as match pattern`
- [ ] compiler/modules/front/codeGen.bal: ``JBUG does not work as match pattern `var { value, multiSemType }` ``
- [ ] compiler/modules/front/codeGen.bal: ``JBUG should be able to use just `var { members }` ``
- [ ] compiler/modules/front/codeGen.bal: `JBUG build fails when the order of binding pattern is reversed`
- [ ] compiler/modules/front/lib.bal: `JBUG temp variable`
- [ ] compiler/modules/front/resolveTypes.bal: `JBUG if this is done with a select, then it gets a bad, sad at runtime if the check gets an error`
- [ ] compiler/modules/front/resolveTypes.bal: `JBUG would like to use match patterns here, but #30718 prevents it`
- [ ] compiler/modules/front/resolveTypes.bal: ``JBUG temp variable `m` is to avoid compiler bug #30736``
- [ ] compiler/modules/front/resolveTypes.bal: ``JBUG temp variable `f` is to avoid compiler bug #30736``
- [ ] compiler/modules/front/tests/testConst.bal: `JBUG error if next line uncommented`
- [ ] compiler/modules/bir/verify.bal: `JBUG #31749 cast should not be needed`
- [ ] compiler/modules/err/err.bal: ``JBUG defining these as `error<Detail> & distinct error` results in these errors not being distinct``
- [ ] compiler/modules/print.llvm/llvm.bal: `JBUG issue:#31767`
- [ ] compiler/modules/print.llvm/llvm.bal: `JBUG #31776 int cast should not be required`
- [ ] compiler/modules/print.llvm/llvm.bal: `JBUG #31777 cast should not be necessary`
- [ ] compiler/modules/print.llvm/llvm.bal: `JBUG 31700 incorrect code generated if 32 is in hex`
- [ ] compiler/modules/print.llvm/llvm.bal: `JBUG #31776 cast should not be necessary`
- [ ] compiler/modules/print.llvm/llvm.bal: `JBUG #31758 type of name[0] is string:Char`
- [ ] compiler/modules/print.llvm/llvm.bal: `JBUG issue:#31767`
- [ ] compiler/modules/front.syntax/token.bal: `JBUG cannot use string:Char #31668 #31660`
- [ ] compiler/modules/front.syntax/token.bal: ``JBUG this avoids bloat that causes `method is too large` errors``
- [ ] compiler/modules/front.syntax/astString.bal: `JBUG cast`
- [ ] compiler/modules/front.syntax/astString.bal: `JBUG cast`
- [ ] compiler/modules/front.syntax/astString.bal: `JBUG cast`
- [ ] compiler/modules/front.syntax/astString.bal: ``JBUG error if `===` used instead if `is` ``
- [ ] compiler/modules/front.syntax/astString.bal: ``JBUG #31775 `foreach var ch in str` gives wrong ch for some str like "\u{10FFFF}""``
- [ ] compiler/modules/front.syntax/parseTypeDesc.bal: `JBUG should not need cast #30191`
- [ ] compiler/modules/front.syntax/ascii.bal: ``JBUG without `int` getting `method is too large` error` ``
- [ ] compiler/modules/front.syntax/parseStmt.bal: `JBUG cast`
- [ ] compiler/modules/front.syntax/parseStmt.bal: `JBUG cast`
- [ ] compiler/modules/front.syntax/scan.bal: `JBUG if this comes before keywords it gets a NPE at module init time`
- [ ] compiler/modules/front.syntax/scan.bal: `JBUG int casts needed`
- [ ] compiler/modules/front.syntax/scan.bal: `JBUG error if hex used for 32 and 128`
- [ ] compiler/modules/front.syntax/scan.bal: `JBUG #31778 shouldn't need this check, fromCodePointInt should return an error`
- [ ] compiler/modules/front.syntax/scan.bal: `JBUG when FragCode is byte, error without cast`
- [ ] compiler/modules/front.syntax/scan.bal: ``JBUG this avoids bloat that causes `method is too large` errors``
- [ ] compiler/modules/front.syntax/parse.bal: `JBUG cast needed #30734`
- [ ] compiler/modules/front.syntax/tests/testParser.bal: `JBUG #31673 can't specify the first type to be "V"|"E"|ect`
- [ ] compiler/modules/front.syntax/tests/testParser.bal: ``JBUG #31988 can't use `suffix ?: ""``
- [ ] compiler/modules/front.syntax/tests/testParser.bal: ``JBUG ballerina-plugin-vscode/#104 can't use string `\` ``
- [ ] compiler/modules/front.syntax/tests/testParser.bal: `JBUG #31444 #31713 #31717 can't write below literals in a simpler way`
- [ ] compiler/modules/front.syntax/tests/testParser.bal: `JBUG moved to a separate method due to method too large, move back to validTokenSourceFragments after beta3`
- [ ] compiler/modules/front.syntax/tests/testParser.bal: `JBUG #31444 #31713 #31717 can't write below literals in a simpler way`
- [ ] compiler/modules/front.syntax/ast.bal: `JBUG #32099 should be "-" `
- [ ] compiler/modules/front.syntax/ast.bal: `JBUG can't include CheckingExpr`
- [ ] compiler/modules/front.syntax/ast.bal: `JBUG adding this field makes match statement in codeGenExpr fail`
- [ ] compiler/modules/front.syntax/ast.bal: `JBUG gets a bad, sad if this uses *MemberAccessExpr and overrides container`

**Comment by KavinduZoysa** [comment]
compiler/tests/baltest.bal // JBUG #33227 semicolon should not be needed
